Milestone 1: Creating REST API with mock data
mariamo14/market-simulator-backend pull request #1
Opened 2024-12-04 20:02 UTC by mariamhio

2024-12-04 20:14 UTC, AbdelrahmanRadwan commented
Add test evidence. One of:

1. Post man request.
2. UI testing.

2024-12-04 20:40 UTC, AbdelrahmanRadwan requested changes

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/model/OrderBookEntry.java
> +        this.volume = volume;
Could be replaced with lombok annotation @getter and @setter or just @data 
https://projectlombok.org/

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/model/OrderBookEntry.java
> +package com.marketdata.MarketSimulatorBackend.api.model;
this should be deleted because it's not used.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/model/StockPrice.java
> +}
can use lombok.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/model/StockPrice.java
> +    public StockPrice(String companyName, double price, String timestamp) {
can used @AllArgsConstructor and @NoArgsConstructor instead.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/service/StockService.java
> +    //make an object of the service inside the controller and return it
todo: create a `List<StockPrice` getMockStockPrices()` method instead of the constructor.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/model/StockPrice.java
> +package com.marketdata.MarketSimulatorBackend.api.model;
this should be in a separate package outside the api package.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/controller/StockController.java
> +        );
instead of this, you need to return `return stockService.getMockStockPrices();`.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/controller/StockController.java
> +@RequestMapping("/api") // Base URL for all endpoints in this controller
can delete the comment.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/api/controller/StockController.java
> +
extra new lines could be deleted.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/main/java/com/marketdata/MarketSimulatorBackend/MarketSimulatorBackendApplication.java
> +
nit: can delete the extra new line.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on src/test/java/com/marketdata/MarketSimulatorBackend/MarketSimulatorBackendApplicationTests.java
> +}
add tests to the other files as well.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on pom.xml
> +	</scm>
Try to delete them and build the project, and if it builds correctly, then you don't really need them.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on pom.xml
> +		</dependency>
always try to add a version of the library.

`<version>`

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on mvnw.cmd
> +<# : batch portion
delete and try to build. If it builds correctly, then it's not needed.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on mvnw
> +#!/bin/sh
delete and try to build. If it builds correctly, then it's not needed.

2024-12-04 20:40 UTC, AbdelrahmanRadwan commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
delete and try to build. If it builds correctly, then it's not needed.

2024-12-11 14:42 UTC, mariamhio commented
> Add test evidence. One of:
> 
> 1. Post man request.
> 2. UI testing.

I’ve tested the endpoint using Postman. Here is the request/response evidence:
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/2dc78a9d-bff0-42bf-b419-b5c9796e7169" />

The data is now reflected in the UI
<img width="586" alt="image" src="https://github.com/user-attachments/assets/de90e667-ff62-410b-8d91-949811858f78" />

2024-12-11 14:48 UTC, mariamhio commented
> Add test evidence. One of:
> 
> 1. Post man request.
> 2. UI testing.

I’ve tested the endpoint using Postman. Here is the request/response evidence:
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/33b3b9ce-9448-4052-9fee-fd37c3db01d3" />


The data is now reflected in the UI
<img width="586" alt="image" src="https://github.com/user-attachments/assets/00df8ac4-5d39-4726-806a-4975c009b9e0" />

2024-12-11 16:55 UTC, merged